### ISSUE TITLE
MetaTogger available in which languages?

### ISSUE THREAD

**Issue by PeterCodar** [CyberSinh/Luminescence.Audio#1]
Maybe you should mention that your software MetaTogger 5.7 is available in German language too?

"Metatogger ia available in English, French, Italiano and Espanol, "
found on http://www.luminescence-software.org/en/metatogger.html

**Comment by CyberSinh** [comment]
You are right. I updated the page. Russian language is coming too...
Keep in mind that this issues tracker is only for the Luminescence.Audio library and not for Metatogger.
