### ISSUE TITLE
Exception executing 'var player = new FFmpegAudioPlayer();' / Audio-Playback not available

### ISSUE THREAD

**Issue by PeterCodar** [CyberSinh/Luminescence.Audio#2]
As soon as I try to execute your example code with 
```
using Luminescence.Audio;

// all audio formats supported by FFmpeg can be played
var player = new FFmpegAudioPlayer();
player.Play(@"C:\MyFolder\MyAudioFile.flac");
```
I get this error in Visual Studio 2015:

> Audio-Playback nicht verfügbar (XAudio2Create, - X).
(nicht verfügbar means ... not available).

What do I have to do to get XAudio2Create get integrated in your compile process for the `Luminescence.Audio.dll`?

**Comment by CyberSinh** [comment]
You must install the XAudio 2.7 runtime on your system to play audio files with the library.

**Comment by PeterCodar** [comment]
Thank you for your answer, CyberSinh (BTW: Great code, thanks for sharing!!)

Do you know any other option then include the redistributable from the linked URLs?
Can we include just the necessary *.DLLs?

**Comment by CyberSinh** [comment]
Unfortunately no, the XAudio runtime is COM dll which require registration in the Windows registry.
