### ISSUE TITLE
"GetFingerprint" is not a Member of "ChromaprintFingerprinter"

### ISSUE THREAD

**Issue by PeterCodar** [CyberSinh/Luminescence.Audio#3]
I assume, your example code should be 
`int[] fingerprint1 = ChromaprintFingerprinter.GetRawFingerprint(@"C:\MyFolder\MyAudioFile1.flac", lengthToFingerprintInSeconds);`

**Comment by CyberSinh** [comment]
Yes, the method has been renamed. I updated the README.
