### ISSUE TITLE
There are 5 additional DLL's required. Where do you get and compile it?

### ISSUE THREAD

**Issue by PeterCodar** [CyberSinh/Luminescence.Audio#5]
This 5 DLL's seemd to be required: 
`avcodec-57.dll, avfilter-6.dll, avformat-57.dll, avutil-55.dll, swresample-2.dll`

You provide them ready-compiled in the directory `Luminescence.Audio/ffmpeg/lib/`

Could you please explain:
a) How do you compile this 5 DLL's in Visual Studio 2015?
(Could you include/link the used source code as you do it for 'chromaprint', 'taglib' and 'zlib'?

b) Where exactly do you need which one of this 5 DLLs?
(Or do you need them all for `/ffmpeg/lib/ffprobe.exe`)

c) Do you see any possibility to include the needed functions from this 5 DLL's in your `Luminescence.Audio.dll`?

**Comment by CyberSinh** [comment]
b) These Dll are [FFmpeg](https://www.ffmpeg.org/), used to decode audio data (used for playing and acoustic fingerprinting). avfilter-6.dll is not required to run Luminescence.Audio.dll

a) You will fing how to compile FFmpeg with Visual Studio [here](https://www.ffmpeg.org/platform.html#Microsoft-Visual-C_002b_002b-or-Intel-C_002b_002b-Compiler-for-Windows). It is not very développer friendly yet.

c) No, to link with FFmpeg MSVC-built static libraries, you will need to make sure you have Runtime Library set to Multi-threaded (/MT) in your project’s settings. And, C++/CLI project only supports dynamic Runtime Library (/MD).
