### ISSUE TITLE
Please add something like ChromaprintFingerprinter.GetRawDuration

### ISSUE THREAD

**Issue by PeterCodar** [CyberSinh/Luminescence.Audio#6]
You already offer the function `ChromaprintFingerprinter.GetRawFingerprint`

If you use fpcalc.exe (chromaprint) with the option -raw on "C:\MyFolder\MyAudioFile1.flac" you get the two values DURATION and FINGERPRINT
DURATION=291
and
FINGERPRINT=...

Could you please add an additional function to get the duration of the fingerprinted file?
Maybe something like `ChromaprintFingerprinter.GetRawDuration`?

With such a function, there would be no need anymore to manually add the length/duration as integer in a lookup with `AcoustidServices.SearchFromFingerprint()`

**Comment by CyberSinh** [comment]
You can get audio file duration by calling TaglibTagger.Duration which returns a TimeSpan.
